### ISSUE TITLE
WifiNiNA cannot handle when the same SSID is broadcasted from multiple APs

### ISSUE THREAD

**Issue by Russell108** [arduino-libraries/WiFiNINA#238] opened 2023-02-04 19:31 UTC
Please can we have an update on this issue
I was told that the issue WifiNiNA cannot handle when the same SSID is broadcasted from multiple APs. would be used to track progress it has not even been assigned to anyone.

**Comment by per1234** [comment] 2023-02-04 19:46
As with your other three issues (https://github.com/arduino-libraries/WiFiNINA/issues/232, https://github.com/arduino-libraries/WiFiNINA/issues/234, https://github.com/arduino-libraries/WiFiNINA/issues/235), closing as duplicate of https://github.com/arduino-libraries/WiFiNINA/issues/200.

@Russell108 you are being disrespectful. If you do this again I will be forced to report your account to GitHub for abuse.

**Closed by per1234** 2023-02-04 19:46 UTC
Labels: type: imperfection
