### ISSUE TITLE
WifiNiNA cannot handle when the same SSID is broadcasted from multiple 

### ISSUE THREAD

**Issue by Russell108** [arduino-libraries/WiFiNINA#234] opened 2023-01-04 21:43 UTC
Please can we have a progress report? 
It's fine locking the issue but it does not really solve anything and with respect, It was not getting to heated. All I did was disagree with someone's opinion. 

Thank you for your understanding and openness to hearing others view points This week I spent $100-00 on Arduino products If you will not allow me to politely share my views I might just see if I can find an alternative eco system. 

I see the original issue was opened in 2021 and it was only when I chirped in that some kind person suggest what was wrong and another kind person asked a team to work on it.  
If you feel I am being unreasonable please feel free to email me directly and let me know, in a kind way, what you object to in my tone, other than seeking a reasonable time frame for a resolution

Best wishes Russell

**Comment by per1234** [comment] 2023-01-04 22:19
Hi @Russell108. GitHub provides a small list of reasons to select when locking a thread and there is no option to write a custom reason. "too heated" is not an accurate description of the reason for locking the thread, but it was the closest reason available. The reason the thread was locked is because it was generating "noise".

The issue trackers are an incredibly valuable tool for getting structured formal feedback from users and tracking work to be done on the project. However, if they are not strictly managed they have a harmful effect on the project. The developers receive a notification every time someone comments on an issue. Reading the notifications takes time and is distracting. We need the developers paying attention to the notifications because they may contain very important information, but we also need them to devote as much time as possible on the essential work on the codebases, so if there is a lot of "noisy" comments in the issue trackers then this is a very serious problem because it wastes Arduino's limited development resources.

Another very serious problem with comments on issues is it makes it very time consuming to review the issue. Essential information might be interspersed with pages and pages of free ranging discussion so we must read through all of it every time.

So when I see an indication that the signal to noise level of an issue is dropping, I lock that issue, and I will continue this practice unapologetically because it is in the best interest of everyone involved with the Arduino project.

>If you will not allow me to politely share my views I might just see if I can find an alternative eco system.

You are welcome to share your views, just not here. Do that on the Arduino Forum:

https://forum.arduino.cc/

---

Closing as duplicate of https://github.com/arduino-libraries/WiFiNINA/issues/200

**Closed by per1234** 2023-01-04 22:19 UTC
